version: 2.0

config: &config
  working_directory: ~/SdkSearch

  docker:
    - image: jakewharton/sdksearch:0.0.3

  environment:
    TERM: dumb
    JAVA_TOOL_OPTIONS: "-Xmx1g"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"


cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}


jobs:
  build:
    <<: *config

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew --stacktrace --init-script init.gradle -Dtrace projectDependencyGraph build :frontend:android:bundle :store:item:android-sql:assembleAndroidTest
          # TODO remove bundle https://issuetracker.google.com/issues/79936441
          # TODO remove assembleAndroidTest https://issuetracker.google.com/issues/80464227
          # TODO remove assembleAndroidTest https://issuetracker.google.com/issues/79934948
      - store_artifacts:
          path: frontend/android/build/outputs/
      - store_artifacts:
          path: frontend/android/build/reports/lint-results.html
      - store_artifacts:
          path: frontend/chrome-extension/build/distributions/
      - store_artifacts:
          path: frontend/web/build/distributions/
      - store_artifacts:
          path: references/legacy-printer/build/distributions/
      - store_artifacts:
          path: references/validator/build/distributions/
      - store_artifacts:
          path: build/commit-timestamp.txt
      - store_artifacts:
          path: build/reports/

      - run:
          name: Aggregate Test Results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp --parents {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper


  validate:
    <<: *config

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew --stacktrace :references:validator:installDist

      - run:
          name: Validate
          command: ./references/validator/build/install/validator/bin/validator | tee >(sed 's/.*\r//' > validation_report.txt)

      - store_artifacts:
          path: validation_report.txt


workflows:
  version: 2

  commit:
    jobs:
      - build

  validation:
    jobs:
      - validate
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
